### ISSUE TITLE
Inline style issue

### ISSUE THREAD

**Issue by ColdFire87** [verico/ng-galleria#4]
The directive sets the inline style of the template to `style="height: 100%; width: 100%"`.

Using the directive as it is triggers the following error in the browser console:

**Fatal error: Could not extract a stage height from the CSS. Traced height: 0px**

To go around that you have to wrap the custom directive in a div and specify the width and height on it.

From [http://galleria.io/docs/getting_started/beginners_guide](http://galleria.io/docs/getting_started/beginners_guide/) ->

> Setting dimensions
> 
> We need to set some dimensions for the gallery. This can be done in many ways, but the simplest is to add some basic CSS rules. Add the following markup inside the <head> tag to apply dimensions and a default black background:
> 
> ```
> <style>
>   .galleria{ width: 700px; height: 400px; background: #000 }
> </style>
> ```
> 
> Galleria will then extract these measures and apply to the gallery.

The fix is to remove in-line styling which overrides the class styles and require the user to style it externally.

**Comment by ColdFire87** [comment]
I've made a pull request to fix the bug
#5 

DON'T MERGE IT!

It fixes the fatal error but breaks responsiveness.
I will investigate the issue further as I try to integrate the directive in my project and let you know whether the issue was in my code or yours

**Comment by ColdFire87** [comment]
Cloning your repository and running the code in isolation seems to be working fine (including using it with bootstrap). I guess the issue lies in integrating it with my code.

**Comment by ColdFire87** [comment]
This issue seems to arise in a lot of situations and has nothing to do with your code. I'm not going to use galleria in my project any more because It's too much work to trace down the bug. Great work anyway... maybe I'll use it in a different project.

You can close the issue and discard the pull request!

**Comment by andwaal** [comment]
Ok thats fine ;)
